# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eb0f7e3a49a0dcb9358c532a15c93049e22c1997ac6b0cdd061bcc782d9b1bbb15b0cf1466e54bc9f02aace30267f133bed1867477f6c00f38abbabe29870a3a

test:
  secret_key_base: c0c7a37d21d70341c3519a5d6bdd68d15732300c4e0b67ac19ecd5b1e85182d036a34730c0afa91a646b7ad13539a8f5410d5cf86d2d8415583ea4fc4800660e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
